import pandas as pd
import smtplib
import glob
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def load_recipients(filepath="recipients.txt"):
    """Reads email addresses from a text file."""
    if not os.path.exists(filepath):
        print(f"Warning: {filepath} not found.")
        return []
    with open(filepath, "r") as f:
        return [line.strip() for line in f if line.strip()]

def generate_html_summary(csv_files):
    """Parses the new CSV format and creates an HTML table."""
    rows_html = ""
    
    for file in csv_files:
        df = pd.read_csv(file)
        
        for _, row in df.iterrows():
            # Sentiment color coding
            op = str(row['Operation']).upper()
            color = "#28a745" if op == "BUY" else "#dc3545"
            
            # Format currency
            val = f"${row['Net Value ($)']:,.2f}"
            
            # Clean up the insiders list for the email (replace semicolons with breaks)
            insiders_list = str(row['Insiders Involved']).replace("; ", "<br>• ")
            
            rows_html += f"""
            <tr style="border-bottom: 1px solid #eee;">
                <td style="padding: 12px; vertical-align: top;"><strong>{row['Company']}</strong></td>
                <td style="padding: 12px; vertical-align: top; color: {color}; font-weight: bold;">{op}</td>
                <td style="padding: 12px; vertical-align: top; text-align: center;">{row['Insiders Count']}</td>
                <td style="padding: 12px; vertical-align: top; text-align: right; font-family: monospace;">{val}</td>
                <td style="padding: 12px; font-size: 11px; color: #666; line-height: 1.4;">• {insiders_list}</td>
            </tr>
            """

    return f"""
    <html>
    <body style="font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f9f9f9;">
        <div style="max-width: 900px; margin: auto; background: white; padding: 20px; border-radius: 8px; border: 1px solid #ddd;">
            <h2 style="color: #004085; border-bottom: 2px solid #004085; padding-bottom: 10px;">Insider Cluster Alert</h2>
            <p>The following high-level insider clusters were identified in the recent filings:</p>
            <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
                <thead>
                    <tr style="background-color: #004085; color: white;">
                        <th style="padding: 12px; text-align: left;">Company</th>
                        <th style="padding: 12px; text-align: left;">Type</th>
                        <th style="padding: 12px; text-align: center;">Count</th>
                        <th style="padding: 12px; text-align: right;">Net Value</th>
                        <th style="padding: 12px; text-align: left;">Insiders Involved</th>
                    </tr>
                </thead>
                <tbody>
                    {rows_html}
                </tbody>
            </table>
            <p style="font-size: 11px; color: #999; margin-top: 30px; text-align: center;">
                Generated by SEC_Insider_Trades Agent
            </p>
        </div>
    </body>
    </html>
    """

def send_emails(html_content, recipients):
    sender = os.getenv("SENDER_EMAIL")
    password = os.getenv("SENDER_PASSWORD")
    
    if not sender or not password:
        print("Error: SMTP credentials missing from environment variables.")
        return

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender, password)

        for email in recipients:
            msg = MIMEMultipart()
            msg['From'] = sender
            msg['To'] = email
            msg['Subject'] = "🚨 High-Level Insider Cluster Detected"
            msg.attach(MIMEText(html_content, 'html'))
            server.send_message(msg)
            print(f"Sent successfully to {email}")
        
        server.quit()
    except Exception as e:
        print(f"Failed to send email: {e}")

if __name__ == "__main__":
    # Look for the new CSV format
    csv_reports = glob.glob("analysis_of_*.csv")
    email_list = load_recipients("recipients.txt")

    if csv_reports and email_list:
        html = generate_html_summary(csv_reports)
        send_emails(html, email_list)
    else:
        if not csv_reports: print("No CSV reports found.")
        if not email_list: print("No recipients found in recipients.txt.")