import json
import smtplib
import glob
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def load_recipients(filepath="recipients.txt"):
    """Reads email addresses from a text file."""
    if not os.path.exists(filepath):
        print(f"Warning: {filepath} not found.")
        return []
    
    with open(filepath, "r") as f:
        # Strip whitespace and ignore empty lines
        emails = [line.strip() for line in f if line.strip()]
    return emails

def generate_html_summary(file_list):
    """Aggregates data from multiple JSON reports into one HTML body."""
    rows_html = ""
    
    # Sort files to ensure consistency
    for file_path in sorted(file_list):
        with open(file_path, 'r') as f:
            try:
                data = json.load(f)
            except:
                continue
            
            for cluster in data:
                color = "#28a745" if cluster['sentiment'] == "BULLISH" else "#dc3545"
                val = f"${cluster['total_net_value']:,.2f}"
                
                rows_html += f"""
                <tr>
                    <td style="padding: 12px; border-bottom: 1px solid #ddd;">{cluster['ticker']}</td>
                    <td style="padding: 12px; border-bottom: 1px solid #ddd;">{cluster['company']}</td>
                    <td style="padding: 12px; border-bottom: 1px solid #ddd; color: {color}; font-weight: bold;">{cluster['sentiment']}</td>
                    <td style="padding: 12px; border-bottom: 1px solid #ddd;">{cluster['insider_count']}</td>
                    <td style="padding: 12px; border-bottom: 1px solid #ddd; text-align: right;">{val}</td>
                </tr>
                """
    
    return f"""
    <html>
    <body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; line-height: 1.6;">
        <div style="max-width: 800px; margin: auto; border: 1px solid #eee; padding: 20px; border-radius: 10px;">
            <h2 style="color: #004085; border-bottom: 2px solid #004085; padding-bottom: 10px;">SEC Insider Trading Alert</h2>
            <p>Multiple high-level clusters detected in the latest filing window:</p>
            <table style="width: 100%; border-collapse: collapse;">
                <thead>
                    <tr style="background-color: #f8f9fa;">
                        <th style="padding: 12px; text-align: left;">Ticker</th>
                        <th style="padding: 12px; text-align: left;">Company</th>
                        <th style="padding: 12px; text-align: left;">Sentiment</th>
                        <th style="padding: 12px; text-align: left;">Insiders</th>
                        <th style="padding: 12px; text-align: right;">Net Value</th>
                    </tr>
                </thead>
                <tbody>
                    {rows_html}
                </tbody>
            </table>
            <footer style="margin-top: 30px; font-size: 11px; color: #888;">
                This automated report monitors Directors, CEOs, CFOs, and COOs. 
                <br>Generated by: <strong>SEC_Insider_Trades Agent</strong>
            </footer>
        </div>
    </body>
    </html>
    """

def send_bulk_emails(html_content, recipient_list):
    """Connects to SMTP once and sends to the entire list."""
    if not recipient_list:
        print("No recipients found. Aborting.")
        return

    # Security: Use GitHub Secrets / Env Vars for your credentials
    SENDER_EMAIL = os.getenv("SENDER_EMAIL")
    SENDER_PASSWORD = os.getenv("SENDER_PASSWORD") 
    
    try:
        # Establish connection once
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)

        for email in recipient_list:
            msg = MIMEMultipart()
            msg['From'] = SENDER_EMAIL
            msg['To'] = email
            msg['Subject'] = f"🚨 Insider Alert: {len(recipient_list)} Targets Identified"
            msg.attach(MIMEText(html_content, 'html'))
            
            server.send_message(msg)
            print(f"Sent to: {email}")

        server.quit()
    except Exception as e:
        print(f"SMTP Error: {e}")

if __name__ == "__main__":
    reports = glob.glob("cluster_analysis*.json")
    recipients = load_recipients("recipients.txt")
    
    if reports and recipients:
        html = generate_html_summary(reports)
        send_bulk_emails(html, recipients)
    else:
        print("Missing reports or recipient list.")